### ISSUE TITLE
When do you plan to release and upload to npm ?

### ISSUE THREAD

**Issue by epicallan** [sparkplug/momoapi-node#1]
This project seems so incomplete, is it meant to be the node mobile money api client ?

**Comment by epicallan** [comment]
This project seems so incomplete, isn't meant to be the node mobile money api ?

**Comment by raybesiga** [comment]
Hi @epicallan 

Thanks for reaching out. I'd like to make a few clarifications. 

1. This repo is not up to date. You will know when we update it.
2. This is not the official Node library for the API. It is a library we are building internally at Sparkplug that we intend to use for the NodeJS training for the API.

Thank you for the enthusiasm and we hope to harness it as we build this library out in the open. Cheers and hopefully see you soon at one of the training.

**Comment by epicallan** [comment]
Alright, thanks for the clarification.

**Comment by raybesiga** [comment]
hi @epicallan have you had a chance to pull from `master` and give the library a try?

**Comment by epicallan** [comment]
Thanks for the heads up, going to look into it again.

**Comment by ernest-okot** [comment]
hey guys, added an issue for the release here #7

**Comment by ernest-okot** [comment]
Closing this in favour of #7
