### ISSUE TITLE
Hande global and product specific variables

### ISSUE THREAD

**Issue by ernest-okot** [sparkplug/momoapi-node#16]
**Is your feature request related to a problem? Please describe.**

Some of the variables required to initialise the library are global, while others are product specific. 

The global variables are;
- Base URL (Sandbox or Production URL)
- Platform Environment (Sandbox or Production)
- Callback Host

The product specific ones are;
- Subscription Key (Primary or Secondary)
- User ID
- User/API Secret

**Describe the solution you'd like**

We should initialise the library with global variables and then initialise the product clients with product-specific variables.

For example;

```js
const momo = require("mtn-momo");

// initialise global variables
const { Collections, Disbursements } = momo(globalVariables); 

// initialise specific product variables
const collections = new Collections(collectionsVariables);
const collections = new Disbursements(disbursementsVariables);
```

**Additional context**

In #9 we discovered that each product requires has it's own subscription, user id and secret

**Comment by raybesiga** [comment]
In this example, did you mean this:

```javascript
const momo = require("mtn-momo");

// initialise global variables
const { Collections, Disbursements } = momo(globalVariables); 

// initialise specific product variables
const collections = new Collections(collectionsVariables);
const disbursements = new Disbursements(disbursementsVariables);
```
Also, care to add an example for what the `collectionsVariables` and `disbursementsVariables` might look like? Thanks
