### ISSUE TITLE
Read token expiry from token

### ISSUE THREAD

**Issue by jkulubya** [sparkplug/momoapi-node#33]
Hi,
I've been taking a look around and I believe that the token that the Momo end points return is a jwt with an "expires" property, in this form:-

```
{
  "clientId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "expires": 1393286893,  --> seconds since epoch
  "sessionId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
}
```

Reading the expiry from the token itself would be more accurate than adding the number of seconds in the response to the current time (eg in the case of a slow network). However, the structure of the token is not explicitly part of the api contract and therefore subject to change, so I don't know how much it can be relied on.

If you do think it's a good idea, it can allow you do a ```currentTime > expires``` check for the expiry and even drop the dependency on moment.

JK

**Comment by ernest-okot** [comment]
Hi JK, 

Yes! It would be more accurate and we can get rid of the moment dependency but then we have to add a dependency to decode the JWT. Moreover, as you mentioned, the token structure being undocumented could break people's code if MTN happens to change it. 

We can store the moment when the token expires instead (minus a few seconds) to cater for the network latency. WDYT?

**Comment by jkulubya** [comment]
Yeah, I think because of its undocumented nature, it's not worth relying on. That's something to give MTN feedback on if you can.

I'm using the "when the token expires instead (minus a few seconds)" approach over [here](https://github.com/jkulubya/mtn-momo-dotnet/blob/efb160cd53c25a00887a7b186fb0ca339181cd6f/MomoApi.NET/BaseApi.cs#L39). 

It's the least bad option

**Comment by ernest-okot** [comment]
Reopening this so that we don't forget to add that improvement

**Comment by ernest-okot** [comment]
@jkulubya we have managed to remove the moment dependency and added the fix to cater for latency. Thanks for bringing this up :tada:
