### ISSUE TITLE
UnspecifiedError.MtnMoMoError

### ISSUE THREAD

**Issue by conradsuuna** [sparkplug/momoapi-node#51]
Anyone managed to use this thing in production?
Thing works well in sandbox but keeps throwing UnspecifiedError.MtnMoMoError error in production.

<img width="594" alt="Screenshot 2021-01-22 at 13 53 47" src="https://user-images.githubusercontent.com/23532840/105482498-7ebdb880-5cb9-11eb-99da-fe85bfb73893.png">
 above is something simple I was trying to do

**Comment by raybesiga** [comment]
Hi @conradsuuna if you read the documentation, it is made clear that the production environment can only be accessed after you [Go Live](https://momodeveloper.mtn.com/go-live). There are specific regulatory requirements that must be fulfilled as specified at that link.  Also, make sure that the `BASE_URL` you supply in the configuration derived from the production dashboard if you set the `environment` to `production`?

**Comment by conradsuuna** [comment]
@raybesiga, I went live last year. I developed an API in python. So I was trying to use this package in my express project. I already have production keys, and 'ericssonbasicapi1.azure-api.net' is the URL I used in my python project. But I've tried it here and all is in vain, still getting the same error. For the target environment, I used 'mtnuganda' in my python project, but it has also thrown the same error when used. I wonder what the problem could be!

**Comment by raybesiga** [comment]
'ericssonbasicapi1.azure-api.net' and  'ericssonbasicapi2.azure-api.net' are different URLs @conradsuuna

**Comment by conradsuuna** [comment]
@raybesiga, you are right, they are different. It's just that in my screenshot, I used  'ericssonbasicapi2.azure-api.net' but I first used  'ericssonbasicapi1.azure-api.net' but still, getting the UnspecifiedError.MtnMoMoError

**Comment by kakoma** [comment]
Hi @conradsuuna ,
I run into this as well. Here's the full error:

```
UnspecifiedError
    at UnspecifiedError.MtnMoMoError [as constructor] (/Path/To/Files/node_modules/mtn-momo/lib/errors.js:21:28)
    at new UnspecifiedError (/Path/To/Files/node_modules/mtn-momo/lib/errors.js:201:47)
    at getError (/Path/To/Files/node_modules/mtn-momo/lib/errors.js:268:12)
    at Object.handleError (/Path/To/Files/node_modules/mtn-momo/lib/errors.js:213:12)
    at /Path/To/Files/node_modules/mtn-momo/lib/client.js:39:150
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

What you could do is open this file `/Path/To/Files/node_modules/mtn-momo/lib/client.js` , go to line 39 and log the full error. Basically, change this:
```
    client.interceptors.response.use(function (response) { return response; }, function (error) {  return Promise.reject(errors_1.handleError(error)); });

```

to this:
```
    client.interceptors.response.use(function (response) { return response; }, function (error) { console.log(error); return Promise.reject(errors_1.handleError(error)); });
```

When you next run it, you'll get the full, very descriptive error. In my case it was:
* message: 'Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription.'* , which is pretty detailed.

**Comment by raybesiga** [comment]
Useful addition @kakoma please make a pull request for this and more additions and we shall endeavor to merge. Best regards.
