### ISSUE TITLE
isPayerActive returns a string instead of a boolean.

### ISSUE THREAD

**Issue by morelmiles** [sparkplug/momoapi-node#67]
**Describe the bug**
The function `isPayerActive` in the `src/collections.ts` dir returns a string. 

**Expected behavior**
Should be returning a boolean (I stand to be corrected). 
Let me know so that I can send a PR right away. 

**Screenshots**
![image](https://user-images.githubusercontent.com/48476293/163379333-f3e3e6e5-7072-4481-902e-2da6cd07b060.png)

**Comment by ernest-okot** [comment]
Looks good @morelmiles, go ahead?

**Comment by morelmiles** [comment]
Cool,will fix it overnight.


---
Luigi Morel.

Software Engineer

Tel: +256 704 916 696 (WhatsApp only)
