### ISSUE TITLE
Add Continuous Integration

### ISSUE THREAD

**Issue by ernest-okot** [sparkplug/momoapi-node#7]
We need to add CI to facilitate automation of testing and npm publishing. I'm thinking we can use Travis although Circle CI will be a viable options as well.

For the start, the CI should publish to NPM when a PR is merged to master.

Progress

- [x] configure tslint
- [x] configure testing
- [ ] configure [semantic release](https://github.com/semantic-release/semantic-release)
- [x] configure [travis ci](travis-ci.org)
- [x] add appropriate npm token and github token to Travis CI secrets

**Comment by raybesiga** [comment]
We still need to figure out if we should use a tool for this or not.

**Comment by ernest-okot** [comment]
At this point, we have two options;

- Tag locally on master and push tags to trigger an NPM publish. This is very simple to do but requires someone with write access to the repo. We could start with this since it's simple and doesn't require any a lot of work but we can get benefits almost immediately
- Integrate semantic-release so that tagging and publishing are both performed automatically when a pull request is merged. This will require some initial setup and change in the workflow but will reduce the workload in the future. It might also be an overkill considering the project and team size. 

Whatever we decide to go with should work

**Comment by raybesiga** [comment]
I say we go with the first option for now though. We can always adapt as we go.
