### ISSUE TITLE
momo-sandbox command no longer works

### ISSUE THREAD

**Issue by dennisja** [sparkplug/momoapi-node#83]
**Describe the bug**
`momo-sandbox` not found in the npm registry

**To Reproduce**
1. Run the command to provision a user (Make sure you have an internet connection and a valid primary key)
```bash
npx momo-sandbox --host example.com --primary-key 23e2r2er2342blahblah
```
2. The error shown in the screenshot will be thrown

**Expected behavior**
Should generate API key and userId

**Screenshots**
<img width="657" alt="Screenshot 2023-04-07 at 09 29 07" src="https://user-images.githubusercontent.com/13004199/230563659-99cc68d7-65f3-49c9-8a74-2c06a602a297.png">

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - npm version 9.6.4

**Comment by ernest-okot** [comment]
Hey @dennisja 

The command is not available in the npm registry, you are supposed to run in the project that has the library installed

**Comment by dennisja** [comment]
Actually, I actually ended up creating a [client here](https://github.com/dennisja/mtn-momo) I can use
