### ISSUE TITLE
Simplify library interface

### ISSUE THREAD

**Issue by ernest-okot** [sparkplug/momoapi-node#9]
Currently, users have to create clients for collections, disbursements, etc, independently like this;

```js
const momoapi = require("momoapi-node");

// Initialise collections
const collections = new momoapi.Collections(config)
// Use collections
momoapi.collections.requestToPay(paymentRequest);

// Initialise disbursements
const disbursements = new momoapi.Disbursements(config)
// Use disbursements
momoapi.disbursements.pay(payoutRequest);
```

This can further be improved such that users configure the library once and use different clients like this;

```js
// Initialize Once
const momoapi = require("momoapi-node")(config);

// Then use
momoapi.collections.requestToPay(paymentRequest);
momoapi.disbursements.pay(payoutRequest);
```

**Comment by raybesiga** [comment]
Interesting approach. Just wondering if it is possible. From what I gather, you need to create a token for each unique product that you subscribe to so unsure about the feasibility of this. Thoughts? @mossplix @ernest-okot

**Comment by ernest-okot** [comment]
@raybesiga as you can see from the first example, the products require configuration to get initialised. 

We have an abstraction for an oauth client. Each product is creating it's own oauth client and defining how it wants the client to retrieve tokens

**Comment by ernest-okot** [comment]
@raybesiga unless you are saying one needs a different userId, userSecret, or subscriptionKey for each product

**Comment by raybesiga** [comment]
Hi @ernest-okot I believe that each product has its own subscription key and that is what is used to with a `UUID` to generate the `userID` and `API Secret` that are used to generate the `Bearer Token`. Am I right @mossplix? Please verify.

**Comment by ernest-okot** [comment]
@raybesiga you are right, each product has an independent subscription. thanks for bringing this up

**Comment by ernest-okot** [comment]
i'm closing this one
